### PR TITLE
Use setCustumUrl to set own url

### PR DESCRIPTION
**Pull request by Shnoulle**
Try to find all interestion information

Todo
- Find is $_SESSION['srid'] is set 
- Fix for plugins (but not for directRequest)
- Adding language ? : but need an option
- Track quota end

### CODE REVIEW

**Comment by Shnoulle** [comment]
PS: i do the beforeQuestionRender next.

Updating an existing script is OK: then we can remove registeredTrackingCode 

# Allways register the tracking code
# unregister in before Survey age (or test directly in afterPluginLoaded ?)

**Comment by SteveCohen** [comment]
Wow. This is fantastic, Denis. It would have taken me years to do that myself! I'm testing these changes now. I agree that removing registedTrackingCode is a good idea.

Will merge once we have beforeQuestionRender because (I think?) this will make URL tracking fully functional.

**Comment by Shnoulle** [comment]
Hi,

I do some fix, but : with beforeQuestionRender : we have more than core google-tracking :)

**Comment by Shnoulle** [comment]
beforeQUestionRender used

**Comment by SteveCohen** [comment]
Very happy to merge this, Denis. :+1:

**Comment by Shnoulle** [comment]
Looking at your idea for completed. Have a "piwikPlugin_Event_Completed" parameters maybe.

Something like:

* Use adapted url : YES/SOME/NO : if no : don't update the url (we have token inside ...) / SOME : use App()->getUrlManager()->parseUrl(App()->getRequest()); without the token (just remove it) and add group/xx/qid/xxx (else we don't have any infprmation)
* Use event : group/completed/ etc .... user can update event name

Maybe to : 

      trackEvent("survey", "completed", "survey-sid");
      trackEvent("survey", "new", "survey-sid");
      trackEvent("survey", "group", "group-gid"); // or 
      trackEvent("survey", "do-".step/maxstep."%", "survey-gid");

etc ....

**Comment by SteveCohen** [comment]
Yes, I agree. I'm currenty working on events and will commit changes soon! Then I'll look at url parameters.

**Pull request merged**
